# ASSIGNMENT : IRIS MULTI-CLASS CLASSIFICATION

###### Purpose :
To predict the species of flower .
###### Description :
The dataset contains a set of 150 records under 5 attributes - Petal Length, Petal Width, Sepal Length, Sepal width and Class(Species).
###### Requirements :
1) Code must be in tf 2.0 .

2) Accuracy must be in between 95-97% .

3) Model shouldn't be Overfit (You can add drop out layer for this) . 

### STEP 1 : Load all the necessary libraries  

In [91]:
import tensorflow as tf
import numpy as np
import pandas as pd
import sklearn

### STEP 2 : Data Preparation
This step consists of multiple sub steps from data loading [download](https://github.com/ramsha275/PIAIC-Sir-Anees-Quarter-2/blob/master/Deep%20Learning/iris.csv),shuffling ,spliting in **Train** and **Test** sets to one-hot-enconding on labels . 
 

In [92]:
iris_df = pd.read_csv("iris.csv")
iris_df.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [93]:
iris_df = iris_df.replace(['Setosa','Versicolor','Virginica'], [0,1,2])
iris_df.head()

sepal.length  sepal.width  petal.length  petal.width  variety
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [94]:
iris_df = sklearn.utils.shuffle(iris_df)
x_train = np.array(iris_df[:113].drop(["variety"],axis=1)) # training dataframe 
y_train = np.array(iris_df[:113]["variety"])             # training labels   # y = labels
x_test = np.array(iris_df[113:].drop(["variety"],axis=1))  # test dataframe
y_test = np.array(iris_df[113:]["variety"])              # test labels       

In [95]:
y_train = tf.keras.utils.to_categorical(y_train)
y_test = tf.keras.utils.to_categorical(y_test)

### STEP 3 : Model Architecture 


###### Input : 4 
###### 1 hidden Layer : 8 nodes
###### Output : 3

In [96]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(128, activation='relu', input_shape=(4,)),
  tf.keras.layers.Dense(3, activation='softmax')
])

### STEP 4 : Compilation Step 

In [97]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [98]:
model.fit(x_train, y_train, epochs=25)

Train on 113 samples
Epoch 1/25
113/113 [==============================] - 1s 10ms/sample - loss: 1.4108 - accuracy: 0.3186
Epoch 2/25
113/113 [==============================] - 0s 168us/sample - loss: 1.2094 - accuracy: 0.1858
Epoch 3/25
113/113 [==============================] - 0s 104us/sample - loss: 1.1231 - accuracy: 0.3363
Epoch 4/25
113/113 [==============================] - 0s 186us/sample - loss: 1.0820 - accuracy: 0.5133
Epoch 5/25
113/113 [==============================] - 0s 177us/sample - loss: 1.0562 - accuracy: 0.3894
Epoch 6/25
113/113 [==============================] - 0s 168us/sample - loss: 1.0171 - accuracy: 0.4956
Epoch 7/25
113/113 [==============================] - 0s 177us/sample - loss: 0.9687 - accuracy: 0.5487
Epoch 8/25
113/113 [==============================] - 0s 142us/sample - loss: 0.9245 - accuracy: 0.4513
Epoch 9/25
113/113 [==============================] - 0s 153us/sample - loss: 0.8901 - accuracy: 0.5044
Epoch 10/25
113/113 [=======================

### STEP 5 : Evaluation  

In [99]:
evaluation = model.evaluate(x_test,  y_test, verbose=2)

37/1 - 0s - loss: 0.4941 - accuracy: 0.9730


### STEP 6 : Prediction 

In [100]:
print('''Actual values : Real Value   Prediction   
                [1. 0. 0.] =     0      = Setosa
                [0. 1. 0.] =     1      = Versicolor
                [0. 0. 1.] =     2      = Virginica''')
print("\nPrediction :")
print("\n->Real value :",y_test[14])
print("\n->Predicted value :",model.predict_classes(x_test[[14]]))

Actual values : Real Value   Prediction   
                [1. 0. 0.] =     0      = Setosa
                [0. 1. 0.] =     1      = Versicolor
                [0. 0. 1.] =     2      = Virginica

Prediction :

->Real value : [1. 0. 0.]

->Predicted value : [0]
